<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
    <AssemblyName>Serpium.SampleEngine</AssemblyName>
    <RootNamespace>Serpium.SampleEngine</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\Build\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SDK\Serpium.Engine.Abstractions\Serpium.Engine.Abstractions.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
