<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>SerpiumUpdater</AssemblyName>
		<AssemblyVersion>1.0.56.13</AssemblyVersion>
		<FileVersion>1.0.56.13</FileVersion>
		<Version>1.0.56.13</Version>
		<VersionPrefix>1.0.56.13</VersionPrefix>
		<VersionSuffix></VersionSuffix>
		<InformationalVersion>1.0.56.13</InformationalVersion>
	</PropertyGroup>

</Project>
